routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::resource('/admin/users',"UsersController");

Route::group(['as' => 'admin.','prefix'=>'admin'],function(){
	Route::resource('categorias','CategoriaController');
    Route::resource('products','ProductsController');

});

Route::group(['route' => 'tienda', 'as' => 'tienda.', 'name' =>'tienda', 'prefix' =>'tienda'],function() {


	Route::get('/','tiendaController@index')->name('index');
	Route::get('products/{id}','tiendaController@show')->name('product.show');
	Route::get('cart','tiendaController@getCart')->name('cart');
	Route::post('cart/add','tiendaController@add')->name('cart.add');
	Route::post('cart/del/{rowId}','tiendaController@del')->name('cart.del');
	Route::get('products','tiendaController@products')->name('products');
	Route::get('checkout','tiendaController@checkout')->name('checkout');
	Route::get('payment','tiendaController@payment')->name('payment');
	Route::get('orders','tiendaController@orders')->name('orders');
	Route::post('payment','tiendaController@execPayment')->name('execPayment');
	Route::get('downloadVoucher/{id}','tiendaController@downloadVoucher')->name('downloadVoucher');
	Route::get('downloadRecibo/{id}','tiendaController@downloadRecibo')->name('downloadRecibo');

});





Route::resource('/admin/clientes',"clienteController");
Route::get('/admin/payments',"paymentController@index")->name('admin.payments.index');
Route::get('/admin/payments/{id}',"paymentController@show")->name('admin.payments.show');
Route::post('/admin/payments/negar/{id}',"paymentController@negar")->name('admin.payments.negar');

Route::get('/admin/payments/confirmar/{id}',"paymentController@confirmar")->name('admin.payments.confirmar');
Route::delete('/admin/payments/confirmar/{id}',"paymentController@destroy")->name('admin.payments.destroy');

//ClientArea
Route::get('/clientarea',"clientareaController@index")->name('clientarea.index');


//Clientarea proyectos
//Payments
Route::get('/clientarea/payments/create',"clientarea\paymentController@create")->name('clientarea.payment.create');
Route::get('/clientarea/payments/store/{id}',"clientarea\paymentController@store")->name('clientarea.payment.store');
Route::get('/clientarea/payments/{id}',"clientarea\paymentController@show")->name('clientarea.payment.show');
Route::get('/clientarea/payments',"clientarea\paymentController@index")->name('clientarea.payment.index');
Route::get('/clientarea/payments/pdf/{id}',"clientarea\paymentController@facturaPDF")->name('clientarea.payment.facturapdf');





Route::get('/admin',"adminController@index")->name('admin.index');




Auth::routes();

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
//Route::get('/home', 'indexController@index')->name('home');
Route::get('/','indexController@index');
Route::middleware('auth')->get('/home',function(){
    
    return Redirect::to('/admin');
});

resources/views/app/admin.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Eventos - Administración</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('css/font-awesome.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('css/AdminLTE.min.css')}}">

    <link rel="stylesheet" href="{{asset('css/bootstrap-select.min.css')}}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{asset('css/_all-skins.css')}}">
    <link rel="apple-touch-icon" href="{{asset('img/apple-touch-icon.png')}}">
    <link rel="shortcut icon" href="{{asset('img/favicon.ico')}}">
    <meta name="csrf-token" content="{{ csrf_token() }}">
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

      <header class="main-header">

        <!-- Logo -->
        <a href="{{route('admin.index')}}" class="logo">
          <!-- mini logo for clientarea mini 50x50 pixels -->
          <span class="logo-mini"><b>V</b>T</span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg">
            <!--b>Ventticket</b-->
            <img width="150px" height="50px" src="{{asset('front/images/ventticket_logo.svg')}}" alt="">
          </span>
        </a>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Navegación</span>
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
              
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  
                  <span class="hidden-xs"><i class="fa fa-user"></i> {{Auth::user()->name}}</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    
                    <p>
                      
                      <small></small>
                    </p>
                  </li>
                  
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    
                    <div class="pull-right">
                      <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="btn btn-default btn-flat">Salir</a>
                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                      </form>
                    </div>
                  </li>
                </ul>
              </li>
              
            </ul>
          </div>

        </nav>
      </header>
      <!-- Left side column. contains the logo and clientarea -->
      <aside class="main-sidebar">
        <!-- clientarea: style can be found in clientarea.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
                    
          <!-- clientarea menu: : style can be found in clientarea.less -->
          <ul class="sidebar-menu">
            <li class="header"></li>
            
            <li class="treeview">
              <a href="#">
                <i class="fa fa-users"></i>
                <span>Clientes</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{{route('clientes.index')}}"><i class="fa fa-circle-o"></i> Ver clientes</a></li>
                
              </ul>
            </li>

            <li class="treeview">
              <a href="#">
                <i class="fa fa-calendar"></i>
                <span>Eventos</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{{route('categorias.index')}}"><i class="fa fa-circle-o"></i> Categorías</a></li>
                <li><a href="{{route('admin.event.index')}}"><i class="fa fa-circle-o"></i> Ver Eventos</a></li>
                
                
              </ul>
            </li>

            <li class="treeview">
              <a href="#">
                <i class="fa fa-dollar"></i>
                <span>Pagos</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{{route('admin.payments.index')}}"><i class="fa fa-circle-o"></i> Pagos</a></li>
                
              </ul>
            </li>

            <li class="treeview">
              <a href="#">
                <i class="fa fa-user"></i>
                <span>Usuarios</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{{route('users.index')}}"><i class="fa fa-circle-o"></i> Usuarios</a></li>
                
              </ul>
            </li>

            <li class="treeview">
              <a href="{{route('admin.checkticket')}}">
                <i class="fa fa-qrcode"></i>
                <span>Escanear Entradas</span>
                
              </a>
           
            </li>
            
                        
          </ul>
        </section>
        <!-- /.clientarea -->
      </aside>





       <!--Contenido-->
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        
        <!-- Main content -->
        <section class="content">
          
          <div class="row">
            <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <h3 class="box-title">Panel de administración</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                  </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                  	<div class="row">
	                  	<div class="col-md-12">
		                          <!--Contenido-->
                              @yield('contenido')
		                          <!--Fin Contenido-->
                           </div>
                        </div>
		                    
                  		</div>
                  	</div><!-- /.row -->
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->

        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      <!--Fin-Contenido-->
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 2.3.0
        </div>
        <strong>Copyright &copy; 2017 
      </footer>

      
    <!-- jQuery 2.1.4 -->
    <script src="{{asset('js/jQuery-2.1.4.min.js')}}"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="{{asset('js/bootstrap.min.js')}}"></script>
    <!-- AdminLTE App -->
    <script src="{{asset('js/app.min.js')}}"></script>
    
    <!-- Axios -->
    <script src="{{asset('js/axios.min.js')}}"></script>
    <script>
      axios.defaults.headers.common['X-CSRF-TOKEN'] = $('meta[name="csrf-token"]').attr('content');
      axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
    </script>
    @stack('scripts')

    
  </body>
</html>

resources/views/app/clientarea.blade.php
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Eventos | Área de Cliente</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.5 -->
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{{asset('css/font-awesome.css')}}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('css/AdminLTE.css')}}">

    <link rel="stylesheet" href="{{asset('css/bootstrap-select.min.css')}}">
    <!-- AdminLTE Skins. Choose a skin from the css/skins
         folder instead of downloading all of them to reduce the load. -->
    <link rel="stylesheet" href="{{asset('css/_all-skins.css')}}">
    <link rel="apple-touch-icon" href="{{asset('img/apple-touch-icon.png')}}">
    <link rel="shortcut icon" href="{{asset('img/favicon.ico')}}">

  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">

      <header class="main-header">

        <!-- Logo -->
        <a href="{{route('admin.index')}}" class="logo">
          <!-- mini logo for clientarea mini 50x50 pixels -->
          <span class="logo-mini"><b>V</b>T</span>
          <!-- logo for regular state and mobile devices -->
          <img width="150px" height="50px" src="{{asset('front/images/ventticket_logo.svg')}}" alt="">
        </a>

        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Navegación</span>
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
              
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  
                  <span class="hidden-xs"><i class="fa fa-user"></i> {{Auth::user()->name}}</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    
                    <p>
                      
                      <small></small>
                    </p>
                  </li>
                  
                  <!-- Menu Footer-->
                  <li class="user-footer">
                    
                    <div class="pull-right">
                      <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="btn btn-default btn-flat">Salir</a>
                          <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                        {{ csrf_field() }}
                      </form>
                    </div>
                  </li>
                </ul>
              </li>
              
            </ul>
          </div>

        </nav>
      </header>
      <!-- Left side column. contains the logo and clientarea -->
      <aside class="main-sidebar">
        <!-- clientarea: style can be found in clientarea.less -->
        <section class="sidebar">
          <!-- Sidebar user panel -->
                    
          <!-- clientarea menu: : style can be found in clientarea.less -->
          <ul class="sidebar-menu">
            <li class="header"></li>
            
            <li class="treeview">
      
              <a href="#">
                <i class="fa fa-calendar"></i>
                <span>Eventos</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{{route('clientarea.event.index')}}"><i class="fa fa-circle-o"></i> Lista</a></li>
                
              </ul>
            </li>

            <li class="treeview">
      
              <a href="#">
                <i class="fa fa-ticket"></i>
                <span>Entradas</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{{route('clientarea.ticket.index')}}"><i class="fa fa-circle-o"></i> Lista</a></li>
                
              </ul>
            </li>
           
           

            <li class="treeview">
              <a href="#">
                <i class="fa fa-dollar"></i>
                <span>Pagos</span>
                <i class="fa fa-angle-left pull-right"></i>
              </a>
              <ul class="treeview-menu">
                <li><a href="{{route('clientarea.payment.index')}}"><i class="fa fa-circle-o"></i> Lista</a></li>
                
              </ul>
              
            </li>

           
                        
          </ul>
        </section>
        <!-- /.clientarea -->
      </aside>





       <!--Contenido-->
      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        
        <!-- Main content -->
        <section class="content">
          
          <div class="row">
            <div class="col-md-12">
              <div class="box">
                <div class="box-header with-border">
                  <h3 class="box-title">Ventticket - Área de Cliente</h3>
                  <div class="box-tools pull-right">
                    <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                    
                    <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
                  </div>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                  	<div class="row">
	                  	<div class="col-md-12">
		                          <!--Contenido-->
                              @yield('contenido')
		                          <!--Fin Contenido-->
                           </div>
                        </div>
		                    
                  		</div>
                  	</div><!-- /.row -->
                </div><!-- /.box-body -->
              </div><!-- /.box -->
            </div><!-- /.col -->
          </div><!-- /.row -->

        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->
      <!--Fin-Contenido-->
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          <b>Version</b> 2.3.0
        </div>
        <strong>Copyright &copy; 2017 
      </footer>

      
    <!-- jQuery 2.1.4 -->
    <script src="{{asset('js/jQuery-2.1.4.min.js')}}"></script>
    <!-- Bootstrap 3.3.5 -->
    <script src="{{asset('js/bootstrap.min.js')}}"></script>
    <!-- AdminLTE App -->
    <script src="{{asset('js/app.min.js')}}"></script>
    
    <!--Start of Tawk.to Script
    <script type="text/javascript">
        
        var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
        Tawk_API.visitor = {
            name  : '{{Auth::user()->name}}',
            email : '{{Auth::user()->email}}'
        };
        (function(){
        var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
        s1.async=true;
        s1.src='https://embed.tawk.to/59762d415dfc8255d623eaef/default';
        s1.charset='UTF-8';
        s1.setAttribute('crossorigin','*');
        s0.parentNode.insertBefore(s1,s0);
        })();
     </script>-->
    
    @stack('scripts')

    
  </body>
</html>