routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::resource('/admin/users',"UsersController");

Route::group(['as' => 'admin.','prefix'=>'admin'],function(){
	Route::resource('categorias','CategoriaController');
    Route::resource('products','ProductsController');

});

Route::group(['route' => 'tienda', 'as' => 'tienda.', 'name' =>'tienda', 'prefix' =>'tienda'],function() {


	Route::get('/','tiendaController@index')->name('index');
	Route::get('products/{id}','tiendaController@show')->name('product.show');
	Route::get('cart','tiendaController@getCart')->name('cart');
	Route::post('cart/add','tiendaController@add')->name('cart.add');
	Route::post('cart/del/{rowId}','tiendaController@del')->name('cart.del');
	Route::get('products','tiendaController@products')->name('products');
	Route::get('checkout','tiendaController@checkout')->name('checkout');
	Route::get('payment','tiendaController@payment')->name('payment');
	Route::get('orders','tiendaController@orders')->name('orders');
	Route::post('payment','tiendaController@execPayment')->name('execPayment');
	Route::get('downloadVoucher/{id}','tiendaController@downloadVoucher')->name('downloadVoucher');
	Route::get('downloadRecibo/{id}','tiendaController@downloadRecibo')->name('downloadRecibo');

});





Route::resource('/admin/clientes',"clienteController");
Route::get('/admin/payments',"paymentController@index")->name('admin.payments.index');
Route::get('/admin/payments/{id}',"paymentController@show")->name('admin.payments.show');
Route::post('/admin/payments/negar/{id}',"paymentController@negar")->name('admin.payments.negar');

Route::get('/admin/payments/confirmar/{id}',"paymentController@confirmar")->name('admin.payments.confirmar');
Route::delete('/admin/payments/confirmar/{id}',"paymentController@destroy")->name('admin.payments.destroy');

//ClientArea
Route::get('/clientarea',"clientareaController@index")->name('clientarea.index');


//Clientarea proyectos
//Payments
Route::get('/clientarea/payments/create',"clientarea\paymentController@create")->name('clientarea.payment.create');
Route::get('/clientarea/payments/store/{id}',"clientarea\paymentController@store")->name('clientarea.payment.store');
Route::get('/clientarea/payments/{id}',"clientarea\paymentController@show")->name('clientarea.payment.show');
Route::get('/clientarea/payments',"clientarea\paymentController@index")->name('clientarea.payment.index');
Route::get('/clientarea/payments/pdf/{id}',"clientarea\paymentController@facturaPDF")->name('clientarea.payment.facturapdf');





Route::get('/admin',"adminController@index")->name('admin.index');




Auth::routes();

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
//Route::get('/home', 'indexController@index')->name('home');
Route::get('/','indexController@index');
Route::middleware('auth')->get('/home',function(){
    
    return Redirect::to('/admin');
});

app/Http/Controllers/tiendaController.php
<?php

namespace App\Http\Controllers;
use App\Categoria;
use App\Products;
use App\Invoice;
use App\InvoiceDetails;
use App\Reservations;
use App\Instapago;
use Illuminate\Http\Request;
use Cart;
use \Instapago\Api;
use PDF;
class tiendaController extends Controller
{

    public function index(Request $request) {

        if (!$request->categoria) {
            $products = Products::where([
                ['name_product','LIKE',"%$request->search%"],
                ['status_id','=',1],
//                ['type','!=',1]
            ])->get();
        }else {

            $products = Products::where([
                    ['name_product','LIKE',"%$request->search%"],
                    ['status_id','=',1],
                    ['categories_id','=',$request->categoria],
//                    ['type','!=',1]
                ]
            )->get();
        }
        
        
    	return view('tienda.index',['products' => $products,'categorias' => Categoria::pluck('categoria','id')]);
    }

    public function execPayment(Request $request) {
        
        $expirationYear = explode("/",$request->expiration);
        $month = $expirationYear[0];
        $year = $expirationYear[1];
        $paymentData = [
          'amount' => \Cart::total(),
          'description' => 'Pago',
          'card_holder' => $request->name,
          'card_holder_id' => $request->cedula,
          'card_number' => str_replace(" ","",$request->card),
          'cvc' => $request->code,
          'expiration' => "$month/20$year",
          'ip' => request()->ip(),
        ];
        try{

          $api = new Api(env('INSTAPAGO_KEY_ID'),env('INSTAPAGO_PUBLIC_KEY_ID'));

          $respuesta = $api->directPayment($paymentData);
          if ($respuesta["code"]==201) {
            $invoice = Invoice::create([
                'code' => 10000,
                'iva' => 16,
                'user_id' => \Auth::user()->id

            ]);
            foreach(Cart::content() as $product) {
                InvoiceDetails::create([
                    'products_id' => $product->options->product["id"],
                    'invoice_id' => $invoice->id,
                    'quantity' => $product->qty,
                    'price' => $product->price
                ]);
            }

            Instapago::create([
                'referencia' => $respuesta["reference"],
                'invoice_id' => $invoice->id,
                'voucher' => $respuesta["voucher"]
            ]);




            Cart::destroy();
            return view('tienda.finish',['voucher' => $respuesta["voucher"],"invoice" => $invoice]);

          }
          // hacer algo con $respuesta
        }catch(\Instapago\Exceptions\InstapagoException $e){

          dd($e->getMessage()); // manejar el error

        }catch(\Instapago\Exceptions\AuthException $e){

          dd($e->getMessage()); // manejar el error

        }catch(\Instapago\Exceptions\BankRejectException $e){

          dd($e->getMessage()); // manejar el error

        }catch(\Instapago\Exceptions\InvalidInputException $e){

          dd($e->getMessage()); // manejar el error

        }catch(\Instapago\Exceptions\TimeoutException $e){

          dd($e->getMessage()); // manejar el error

        }catch(\Instapago\Exceptions\ValidationException $e){

          dd($e->getMessage()); // manejar el error

        }
        dd($paymentData);
        //return view('tienda.payment');
    }
    public function payment() {
        if(count(Cart::content())<1) {
            return redirect('tienda');
        }
        return view('tienda.payment');
    }
    public function cart(Request $request) {
        $product = '';
        if ($request->has('id')){
            $product = Products::findOrFail($request->id);
            if (!$product) { return response(['status' => 'error'],403); }
        }else {

        }


        switch($request->action) {
            case 'add':
                if ($request->options["alquiler"]) {
                    if (!$request->options["address"] || !$request->options["horas"] || !$request->options["start_time"] || !$request->options["end_time"]) {
                        return response(['status' => 'error','msg' => "Ingrese todos los datos"],403);
                    }

                    $horas = $request->options["horas"];
                    $start_time = $request->options["start_time"];
                    $end_time = $request->options["end_time"];
                    $address = $request->options["address"];
                    $fecha = $request->options["fecha"];
                    $sale_price = $request->options["sale_price"];
                    $res = Reservations::where('fecha','=',$request->options["fecha"])->get()->count();
                    if ($res>=$product->stock) {
                        return response(['status' => 'error','msg' => "El producto \"$product->name_product\" no está disponible para la fecha $fecha"],403);

                    }

                    $p = Cart::search(function ($cartItem, $rowId) use ($request) {
                        return $cartItem->id === $request->id;
                    });

                    if (count($p)<1) {
                        Cart::add($request->id,"(Alquiler) ".$product->name_product, $request->quantity, $request->options["total"],['image' => $product->image,'alquiler' => true,'horas' => $horas,'fecha' => $fecha, 'end_time' => $end_time,'start_time' => $start_time,'address' => $address,'sale_price' => $sale_price ]);
                    }else {
                        return response(['status' => 'error','msg' => "El producto \"$product->name_product\" ya está registrado en el carrito"],403);
                    }
                }else {
                    Cart::add($request->id,$product->name_product, $request->quantity, $product->sale_price,['image' => $product->image]);
                }

                return response(['action' => $request->action,'product' => $product,'cart' => Cart::content(),'total' => Cart::subtotal()]);
                break;

            case 'remove':
                Cart::remove($request->code);
                return response(['action' => $request->action,'product' => $product,'cart' => Cart::content(),'total' => Cart::subtotal()]);
                break;
            case 'empty':
                Cart::destroy();
                return response(['action' => $request->action]);
                break;
        }
    }

    public function checkout() {
        //dd(Cart::content());

        return view('tienda.checkout');
    }


    public function downloadRecibo($id) {

        $invoice = Invoice::with('instapago','details','user')->findOrFail($id);
        //$pdf = App::make('dompdf.wrapper');
        //$pdf->loadHTML('<h1>Test</h1>');
        //return $pdf->stream();
        $pdf = PDF::loadView('pdf.factura', compact('invoice'));
        return $pdf->stream('invoice.pdf');
    }

    public function downloadVoucher($id) {

        $invoice = Invoice::with('instapago')->findOrFail($id);
        //$pdf = App::make('dompdf.wrapper');
        //$pdf->loadHTML('<h1>Test</h1>');
        //return $pdf->stream();

        $pdf = PDF::loadHTML($invoice->instapago->voucher);
        return $pdf->stream("voucher-$invoice->code.pdf");
    }

    public function show($id) {
        $product = Products::findOrFail($id);
        return view('tienda.showproduct',['product' => $product]);
    }
  
    public function add(Request $request) {
        $product = Products::findOrFail($request->id);

        parse_str($request->options, $options);

        $options["product"] = $product;
        $c = Cart::add($product->id,$product->name_product,$request->qty,$request->orderPrice,$options);
        Cart::setTax($c->rowId,16);
        return ["success" => true,"c" => $c];
    }
    public function getCart() {
        return Cart::content();
    }
    public function del(Request $request,$rowId) {
        $c = Cart::remove($rowId);
        return ["success" => true,"c" => $c];

    }
    public function products() {
        return Products::all();
    }


    public function orders() {
        $orders = \Auth::user()->invoices;

        $orders->load('details','instapago','details.product');

        
        return view('tienda.orders',compact('orders'));

    }
}

resources/views/tienda/checkout.blade.php
@extends('layouts.tienda.template')

@section('content')
	
	<section class="section-content bg padding-y border-top">
   <div class="container">
      <div class="row">
         @if(count(Cart::content())>0)
         <main class="col-sm-9">
            <div class="card">
               <table class="table table-hover shopping-cart-wrap">
                  <thead class="text-muted">
                     <tr>
                        <th scope="col">Producto</th>
                        <th scope="col" width="160">Precio Unit. (+IVA)</th>
                        <th scope="col" width="120">Cantidad</th>
                        <th scope="col" width="120">Total</th>
                     </tr>
                  </thead>
                  <tbody>
                    @foreach(Cart::content() as $product)
                      @php
                         $iva = 16;
                         $precioIva = $product->price*$iva/100;
                         $total = $product->price+$precioIva;
                       @endphp

                     <tr>
                        <td>
                           <figure class="media">
                              <div class="img-wrap"><img src="{{asset("images/products/".$product->options->product->image)}}"  class="img-thumbnail img-sm"></div>
                              <figcaption class="media-body">
                                 <h6 class="title text-truncate">{{$product->name}}</h6>
                               
                              </figcaption>
                           </figure>
                        </td>
                         <td>
                           <div class="price-wrap"> 
                              <var class="price">{{$total}} Bs.S</var> 
                           </div>
                           <!-- price-wrap .// -->
                        </td>
                        <td>
                           <select class="form-control" disabled>
                              <option>{{$product->qty}}</option>
                             
                           </select>
                        </td>
                        <td>
                           <div class="price-wrap"> 
                              <var class="price">{{$product->total}} Bs.S</var> 
                           </div>
                           <!-- price-wrap .// -->
                        </td>
                      
                     </tr>
                 
                 	@endforeach
                  </tbody>
               </table>
            </div>
            <!-- card.// -->
         </main>
         <!-- col.// -->
         <aside class="col-sm-3">
          
            <dl class="dlist-align">
               <dt>Sub-Total </dt>
               <dd class="text-right">{{Cart::subtotal()}} Bs.S</dd>
            </dl>
            <dl class="dlist-align">
               <dt>IVA:</dt>
               <dd class="text-right">{{Cart::tax()}} Bs.S</dd>
            </dl>
            <dl class="dlist-align h5">
               <dt>Total:</dt>
               <dd class="text-right"><strong>{{Cart::total()}} Bs.S</strong></dd>
            </dl>
            <hr>
            
            

            @if(\Auth::user())
            <a href="{{route('tienda.payment')}}" class="btn btn-primary btn-block">Pagar</a>
            @else
            
              <p>Debes logearte o <a href="{{route('register')}}">registrarte</a> para hacer tu pedido</p>
            @endif

            
         </aside>
         
         @else
            <h3>No tienes productos registrados, <a href="{{url('tienda')}}">añade algunos</a>.</h3>
         @endif
         <!-- col.// -->
      </div>
   </div>
   <!-- container .//  -->
</section>
@endsection

resources/views/tienda/finish.blade.php
@extends('layouts.tienda.template')

@section('content')
	
	<div class="container">
		<div class="row justify-content-center">
			{{--!! $voucher !!--}}

			<h1>Tu pedido ha sido completado, N° {{$invoice->code}}</h1>

		</div>
		
			<div class="row">
				<a href="{{route('tienda.downloadVoucher',$invoice->id)}}" class="btn btn-primary" download><i class="fa fa-download"></i> Descargar voucher</a>
			</div>
			<div class="row">
				<a href="{{route('tienda.downloadRecibo',$invoice->id)}}" class="btn btn-primary" download><i class="fa fa-download"></i> Descargar recibo</a>
			</div>

	</div>

@endsection

resources/views/tienda/index.blade.php
@extends('layouts.tienda.template')

@section('content')

<div class="container">
        <div class="card">
           <div class="card-body">
        
              <hr>
              <div class="row">
                 <!-- col.// -->
                   <div class="col-lg-4-24 col-sm-3">
                     <div class="category-wrap dropdown py-1">
                        <button type="button" class="btn btn-light  dropdown-toggle" data-toggle="dropdown" ><i class="fa fa-bars"></i> {{ Request::query('categoria') ? $categorias[Request::query('categoria')] : 'Categorías' }}</button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{{url("tienda/")}}">Ninguna</a>
                          
                           @foreach($categorias as $id => $categoria)

                              <a class="dropdown-item {{Request::query('categoria') == $id ? 'active' : ''}}" href="{{url("tienda/?categoria=$id")}}">{{$categoria}}</a>
                          
                           @endforeach

                        </div>
                     </div>
                  </div>
                  <div class="col-lg-10 col-sm-10">
                     <form action="" class="py-1">
                        <div class="input-group w-100">
                         
                           <input type="text" class="form-control" style="width:50%;" placeholder="Buscar" name="search" value="{{Request::query('search')}}">
                           <div class="input-group-append">
                              <button class="btn btn-primary" type="submit">
                              <i class="fa fa-search"></i> Buscar 
                              </button>
                           </div>
                        </div>
                     </form>
                     <!-- search-wrap .end// -->
                  </div>
                 <!-- col.// -->
              </div>
              <!-- row.// -->
           </div>
           <!-- card-body .// -->
        </div>
        <!-- card.// -->

        @if(Request::query('categoria'))
          <div class="padding-y-sm">
             <span>Categoría: {{$categorias[Request::query('categoria')]}}</span>	
          </div>
        @endif
         <div class="row-sm pt-3 mt-3">

        @foreach($products as $product)
        @php
          $iva = 16;
          $precioIva = $product->sale_price*$iva/100;
          $total = $product->sale_price+$precioIva;
        @endphp
            <div class="col-md-3 col-sm-6 ml-4">
               <figure class="card card-product">
               <div class="img-wrap"> <img src="{{asset("images/products/$product->image")}}"></div>
                  <figcaption class="info-wrap">
                  <a href="{{url("tienda/products/$product->id")}}" class="title">{{$product->name_product}}</a>
                     <div class="price-wrap">
                        <span class="price-new">{{$total}} Bs.S <br> <small class="price-old">IVA (16%): {{$precioIva}} Bs.S</small></span>
                        {{-- <del class="price-old">$1980</del> --}}
                     </div>
                     <!-- price-wrap.// -->
                  </figcaption>
               </figure>
               <!-- card // -->
            </div>

            <!-- col // -->
         @endforeach
                  </div>

        <!-- row.// -->
     </div>
@endsection

resources/views/tienda/orders.blade.php
@extends('layouts.tienda.template')

@section('content')
	
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-md-12">
				<table class="table  table-striped">
			<thead>
				<th>Código</th>
				<th>Fecha</th>
				<th>Pagado</th>
				<th width="250">Acciones</th>
			</thead>


			<tbody>
				@foreach($orders as $o) 

					<tr>
						<td>{{$o->code}}</td>
						<td>{{$o->created_at}}</td>
						<td>{{$o->total}} Bs.S</td>
						<td>
							<button data-toggle="modal" data-target="#modal-show-{{$o->id}}" class="btn btn-primary"><i class="fa fa-eye"></i></button>
							<a download href="{{route('tienda.downloadVoucher',$o->id)}}" class="btn btn-success">Voucher</a>
							<a download href="{{route('tienda.downloadRecibo',$o->id)}}" class="btn btn-warning">Recibo</a>
						</td>
					</tr>

						@push('modals')


							<div class="modal fade modal-slide-in-right" aria-hidden="true"
						role="dialog" tabindex="-1" id="modal-show-{{$o->id}}">
							
							<div class="modal-dialog modal-lg">
								<div class="modal-content">
								<div class="modal-header">
							          <button type="button" class="close" data-dismiss="modal">&times;</button>
							          <h4 style="color:red;"><span class="glyphicon glyphicon-lock"></span> Ver orden</h4>
							        </div>
									<div class="modal-body">
										<table class="table table-striped">
											 <table class="table table-hover shopping-cart-wrap">
						                  <thead class="text-muted">
						                     <tr>
						                     	<th scope="col">Nombre</th>
						                        <th scope="col">Imagen</th>
						                        <th scope="col" width="160">Precio Unit. (+IVA)</th>
						                        <th scope="col" width="120">Cantidad</th>
						                        <th scope="col" width="120">Total</th>
						                     </tr>
						                  </thead>
						                  <tbody>
						                    @foreach($o->details as $product)
						                      @php
						                         $iva = 16;
						                         $precioIva = $product->price*$iva/100;
						                         $total = $product->price+$precioIva;
						                       @endphp

						                     <tr>
					                     	   <td>
						                         {{$product->product->name_product}}
						                           <!-- price-wrap .// -->
						                        </td>
						                        <td>
						                           <figure class="media">
						                              <div class="img-wrap"><img src="{{asset("images/products/".$product->product->image)}}"  class="img-thumbnail img-sm"></div>
						                              <figcaption class="media-body">
						                                 <h6 class="title text-truncate">{{$product->product->name}}</h6>
						                               
						                              </figcaption>
						                           </figure>
						                        </td>
						                         <td>
						                           <div class="price-wrap"> 
						                              <var class="price">{{$total}} Bs.S</var> 
						                           </div>
						                           <!-- price-wrap .// -->
						                        </td>
						                        <td>
						                           <var class="price">{{$product->quantity}}</var>
						                        </td>
						                        <td>
						                           <div class="price-wrap"> 
						                              <var class="price">{{$total * $product->quantity}} Bs.S</var> 
						                           </div>
						                           <!-- price-wrap .// -->
						                        </td>
						                      
						                     </tr>
						                 
						                 	@endforeach
						                  </tbody>
						               </table>
									</div>
									<div class="modal-footer">
										<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
									</div>
								</div>
							</div>
							

						</div>

						@endpush
				@endforeach
			</tbody>
				</table>
			</div>
		</div>

	</div>




@endsection

resources/views/tienda/showproduct.blade.php
@extends('layouts.tienda.template')


@section('content')
    <section class="section-content bg padding-y-sm">
        <div class="container">
          
           <div class="row">
              <div class="col-xl-10 col-md-9 col-sm-12">
                 <main class="card">
                    <div class="row no-gutters">
                       <aside class="col-sm-6 border-right">
                          <article class="gallery-wrap">
                             <div class="img-big-wrap">
                                <div> <a href="{{asset("images/products/$product->image")}}" data-fancybox=""><img src="{{asset("images/products/$product->image")}}"></a></div>
                             </div>
                             <!-- slider-product.// -->
                             <div class="img-small-wrap">
                              <div class="item-gallery"> <img src="{{asset("images/products/$product->image")}}"></div>
                               
                             </div>
                          </article>
                       </aside>
                       <aside class="col-sm-6">
                          <article class="card-body">
                             <!-- short-info-wrap -->
                             <h3 class="title mb-3">{{$product->name_product}}</h3>
                             <div class="mb-3"> 
                                <var class="price h3 text-warning"> 
                                <span class="currency">Bs.S </span><span class="num">{{$product->sale_price}}</span>
                                </var> 
                                
                             </div>
                             <!-- price-detail-wrap .// -->
                             <dl>
                                <dt>Description</dt>
                                <dd>
                                   <p>{!! $product->descripcion !!}
                                   </p>
                                </dd>
                             </dl>
                          
                             <!-- rating-wrap.// -->
                             <hr>
                             <div class="row">
                                <div class="col-sm-5">
                                   <dl class="dlist-inline">
                                      <dt>Cantidad: </dt>
                                      <dd>
                                         <select id="qty" class="form-control form-control-sm" style="width:70px;">
                                             @for ($i = 0; $i < 20; $i++)
                                                <option value="{{$i}}">{{$i}}</option>
                                             @endfor  
                                          
                                             
                                         </select>
                                      </dd>
                                   </dl>
                                   <!-- item-property .// -->
                                </div>
                                <!-- col.// -->
                                
                                <!-- col.// -->
                             </div>
                             <!-- row.// -->
                             <hr>
                             <a href="javascript:void(0)" onclick="agregarProducto()" class="btn  btn-outline-warning"> Añadir al carrito </a>
                             <!-- short-info-wrap .// -->
                          </article>
                          <!-- card-body.// -->
                       </aside>
                       <!-- col.// -->
                    </div>
                    <!-- row.// -->
                 </main>
              
              </div>
         
              <!-- col // -->
           </div>
           <!-- row.// -->
        </div>
        <!-- container // -->
     </section>

    
      <script>
         function agregarProducto() {

         
            var productId = '{{$product->id}}';
            var qty = $("#qty").val();
            if (!qty || qty ==0) {
               toastr.error('Especifica una cantidad válida');
               return;
            }
            var price = {{$product->sale_price}};
            var options =
            addToCart(productId,qty,price); 
         }
      </script>
@endsection