routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::resource('/admin/users',"UsersController");

Route::group(['as' => 'admin.','prefix'=>'admin'],function(){
	Route::resource('categorias','CategoriaController');
    Route::resource('products','ProductsController');

});

Route::group(['route' => 'tienda', 'as' => 'tienda.', 'name' =>'tienda', 'prefix' =>'tienda'],function() {


	Route::get('/','tiendaController@index')->name('index');
	Route::get('products/{id}','tiendaController@show')->name('product.show');
	Route::get('cart','tiendaController@getCart')->name('cart');
	Route::post('cart/add','tiendaController@add')->name('cart.add');
	Route::post('cart/del/{rowId}','tiendaController@del')->name('cart.del');
	Route::get('products','tiendaController@products')->name('products');
	Route::get('checkout','tiendaController@checkout')->name('checkout');
	Route::get('payment','tiendaController@payment')->name('payment');
	Route::get('orders','tiendaController@orders')->name('orders');
	Route::post('payment','tiendaController@execPayment')->name('execPayment');
	Route::get('downloadVoucher/{id}','tiendaController@downloadVoucher')->name('downloadVoucher');
	Route::get('downloadRecibo/{id}','tiendaController@downloadRecibo')->name('downloadRecibo');

});





Route::resource('/admin/clientes',"clienteController");
Route::get('/admin/payments',"paymentController@index")->name('admin.payments.index');
Route::get('/admin/payments/{id}',"paymentController@show")->name('admin.payments.show');
Route::post('/admin/payments/negar/{id}',"paymentController@negar")->name('admin.payments.negar');

Route::get('/admin/payments/confirmar/{id}',"paymentController@confirmar")->name('admin.payments.confirmar');
Route::delete('/admin/payments/confirmar/{id}',"paymentController@destroy")->name('admin.payments.destroy');

//ClientArea
Route::get('/clientarea',"clientareaController@index")->name('clientarea.index');


//Clientarea proyectos
//Payments
Route::get('/clientarea/payments/create',"clientarea\paymentController@create")->name('clientarea.payment.create');
Route::get('/clientarea/payments/store/{id}',"clientarea\paymentController@store")->name('clientarea.payment.store');
Route::get('/clientarea/payments/{id}',"clientarea\paymentController@show")->name('clientarea.payment.show');
Route::get('/clientarea/payments',"clientarea\paymentController@index")->name('clientarea.payment.index');
Route::get('/clientarea/payments/pdf/{id}',"clientarea\paymentController@facturaPDF")->name('clientarea.payment.facturapdf');





Route::get('/admin',"adminController@index")->name('admin.index');




Auth::routes();

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');
//Route::get('/home', 'indexController@index')->name('home');
Route::get('/','indexController@index');
Route::middleware('auth')->get('/home',function(){
    
    return Redirect::to('/admin');
});

resources/views/admin/check.blade.php
@extends('layouts.admin.template')

@section('contenido')

  <h2 class="text-center">Canjear Entrada</h2>  
  <div class="col-sm-12">
    <div id="reader" style="width:300px;height:250px;margin:auto;"></div>
  </div> 

  <h3 class="text-center">Escanee el código QR de la entrada</h3>

  <h5 class="text-center">Puedes escribirlo manualmente</h5>
  <div class="col-sm-4 col-sm-offset-4">
	<div class="form-group">
	  	<div class="input-group">
		  	<input type="text" class="form-control" name="codigo" id="codigo">
			  <span class="input-group-btn"><button class="btn btn-primary" id="btn-codigo">Escanear</button></span>
		  </div>
  	</div>
  </div>

  <div id="result" class="col-sm-4 col-sm-offset-4" style="display: none">
   
  </div>

  <div class="modal fade modal-slide-in-right" aria-hidden="true" role="dialog" tabindex="-1" id="modal-canje">
  

	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" 
				aria-label="Close">
                     <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Canje de entrada</h4>
			</div>
			<div class="modal-body">
          <h3 class="text-center">¡Entrada Canjeada!</h3>
          
          <p  class="text-center" style="color: #4eb981; font-size: 150px; margin:auto; text-align: center;"><i class="fa fa-check-circle"></i></p>
          <br>
          <p><strong>Evento:</strong> <span id="evento"></span></p>
          <p><strong>Código de la entrada:</strong> <span id="cod_entrada"></span></p>
          <p><strong>Tipo de entrada:</strong> <span id="tipo_entrada"></span></p>
          
          <h4>Datos personales del cliente:</h4>
          <p><strong>Nombre y Apellido: </strong> <span id="cliente_nombre"></span></p>
          <p><strong>Cédula: </strong> <span id="cliente_cedula"></span></p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				
			</div>
		</div>
	</div>
	
</div>

<div class="modal fade modal-slide-in-right" aria-hidden="true"
role="dialog" tabindex="-1" id="modal-invalido">
  

	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" 
				aria-label="Close">
                     <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Código invalido</h4>
                
			</div>
			<div class="modal-body">
          <h3>El código no hace referencia a ninguna entrada</h3>
         
          <p  class="text-center" style="color: #8f103b; font-size: 150px; margin:auto; text-align: center;"><i class="fa fa-exclamation-triangle "></i></p>
          <br>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				
			</div>
		</div>
  </div>
  	

</div>

<div class="modal fade modal-slide-in-right" aria-hidden="true"
role="dialog" tabindex="-1" id="modal-canjeada">
  

	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" 
				aria-label="Close">
                     <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Entrada canjeada</h4>
                
			</div>
			<div class="modal-body">
          <h3>La entrada ya fue canjeada</h3>
         
          <p  class="text-center" style="color: #8f103b; font-size: 150px; margin:auto; text-align: center;"><i class="fa fa-exclamation-triangle "></i></p>
          <br>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				
			</div>
		</div>
  </div>
  	

</div>

<div class="modal fade modal-slide-in-right" aria-hidden="true"
role="dialog" tabindex="-1" id="modal-inexistente">
  

	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" 
				aria-label="Close">
                     <span aria-hidden="true">×</span>
                </button>
                <h4 class="modal-title">Entrada inexistente</h4>
                
			</div>
			<div class="modal-body">
          <h3>Esta entrada no existe en nuestra base de datos</h3>
         
          <p  class="text-center" style="color: #8f103b; font-size: 150px; margin:auto; text-align: center;"><i class="fa fa-exclamation-triangle "></i></p>
          <br>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
				
			</div>
		</div>
  </div>
  	

</div>


@push('scripts')
    <script src="{{asset('js/jsqrcode-combined.min.js')}}"></script>
    <script src="{{asset('js/html5-qrcode.min.js')}}"></script>
    <script> var url = '{{ url('/admin/checkentrada?codigo=')}}';</script>
	<script src="{{asset('js/scan.js')}}"></script>
	<script>

		$("#btn-codigo").click(function() {
			codigoManual();
		});
		function codigoManual() {
			codigo = $("#codigo").val();
			ajaxEntrada(codigo);
		}
		$("#codigo").keydown(function(e) {
			if (e.keyCode == 13) {
				codigoManual();
			}
		});
	</script>
@endpush
@endsection

    


    

      

resources/views/admin/index.blade.php
@extends('layouts.admin.template')


@section('contenido')
    
  
    <div class="rosw">
        <div class="col-sm-12 col-md-12 col-lg-12 col-xs-12">
                
            <div class="card ">

                <div class="card-header" style=""><h3>Menú de opciones</h3></div>           
                <div class="card-body">
                        <div class="text-center">
                        <div class="row">
                            <div class="col-sm-3 col-xs-12">
                                <div class="menu-item">
                                    <a href="{{route('clientes.index')}}">
                                        <div class="menu-item-content">

                                                <span class="menu-item-icon"><span class="fa fa-users"></span></span>
                                                <h5>Clientes</h5>

                                        </div>
                                    </a>
                                </div>
                            </div>

                            <div class="col-sm-3">
                                <div class="menu-item">
                                    <a href="{{route('admin.products.index')}}">
                                        <div class="menu-item-content">

                                            <span class="menu-item-icon"><span class="fa fa-th-list"></span></span>
                                            <h5>Productos</h5>
                                        </div>
                                    </a>


                                </div>
                            </div>
                            
                            <div class="col-sm-3">
                                <div class="menu-item">
                                    <a href="{{route('admin.payments.index')}}">
                                        <div class="menu-item-content">

                                    


                                            <span class="menu-item-icon"><span class="fa fa-dollar-sign"></span></span>
                                            <h5>Pagos</h5>

                                        </div>
                                    </a>
                                </div>
                            </div>

                            <div class="col-sm-3">
                                <div class="menu-item">
                                    <a href="{{route('users.index')}}">
                                        <div class="menu-item-content">

                                            <span class="menu-item-icon"><span class="fa fa-user"></span></span>
                                            <h5>Usuarios</h5>

                                        </div>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div> 
                </div>
            </div>
     
    </div>

    </div>

    <style>




        .menu-item {
            margin: 20px;
            text-align: center;
            background-color: #6f69e4;
            color: white;
            /*! padding-bottom: 8px; */
            border-radius: 5px;
            box-shadow:1px 1px 10px #DDDDDD;
            height: 100px;
        }
        .menu-item a {
            text-decoration: none;
            color: white;
            transition: all 0.3s ease;
        }

        .menu-item-icon {

            font-size: 50px;
        }
        .menu-item h5 {s
            font-size: 15px;
            font-weight: bold;
            color: white;
            transition: all 0.3s ease;
        }
        .menu-item a:hover {
            color: #DDDDDD;
        }





    </style>
       
    
@endsection